simulation_metadata:
  device: 'cpu'
  num_episodes: 1
  num_steps_per_episode: 50
  num_substeps_per_step: 3
  calibration: false
  visualize: true
  num_bap: 50  # Number of consumers
  num_bpp: 0  # Not used in scripts
  num_order: 99999

state:
  environment:
    restock_threshold:
      name: "Restock Threshold"
      value: 20  # Minimum stock before restocking
    restock_quantity:
      name: "Restock Quantity"
      value: 100  # Units to restock
    products:
      name: "Products"
      value:
        - id: 1
          name: "Product A"
          price: 20
          stock: 10  # Reduced to trigger restocking
        - id: 2
          name: "Product B"
          price: 15
          stock: 5   # Reduced to trigger restocking
        - id: 3
          name: "Product C"
          price: 10
          stock: 50
    last_order_id:
      name: "Last Created Order"
      value: -1

  agents:
    bap:  # Consumers
      number: 50
      properties:
        id:
          name: "Consumer ID"
          initialization_function:
            generator: "generate_ids"
            arguments:
              shape:
                - 50
                - 1
        budget:
          name: "Budget"
          initialization_function:
            generator: "random_float"
            arguments:
              lower_limit:
                name: "Lower Limit"
                value: 50
              upper_limit:
                name: "Upper Limit"
                value: 200
        price_sensitivity:
          name: "Price Sensitivity"
          initialization_function:
            generator: "random_float"
            arguments:
              lower_limit:
                name: "Lower Limit"
                value: 0.5
              upper_limit:
                name: "Upper Limit"
                value: 1.5

# Substep Definitions
substeps:
  '0':  # Restock Step
    type: observation
    name: restock
    description: "Restock products when stock is below the threshold."
    active_agents:
      - environment
    observation:
      environment:
        check_stock_levels:
          generator: "Restock"
          input_variables:
            - "environment"
          output_variables:
            - "environment"

  '1':  # Purchase Step
    type: policy
    name: purchase
    description: "Consumers decide what products to purchase."
    active_agents:
      - bap
    policy:
      consumer:
        make_purchase_decision:
          generator: "Purchase"
          input_variables:
            - "agents"
            - "environment"
          output_variables:
            - "actions"

  '2':  # Deliver Step
    type: transition
    name: deliver
    description: "Deliver products to consumers and update stock."
    active_agents:
      - environment
    transition:
      environment:
        deliver_products:
          generator: "Deliver"
          input_variables:
            - "environment"
            - "actions"
          output_variables:
            - "environment"

promotions:
  - id: 1
    discount: 0.2  # 20% off Product A
    duration: 7
  - id: 2
    discount: 0.1  # 10% off Product B
    duration: 14

consumers:
  count: 50  # Replaced variable reference with actual value
  budget_range:
    min: 50
    max: 200
  price_sensitivity_range:
    min: 0.5
    max: 1.5
  purchase_frequency_range:
    min: 2
    max: 5

