# Simulation Configuration
simulation:
  steps: 10  # Number of steps to run the simulation

# Simulation Metadata
simulation_metadata:
  num_steps_per_episode: 10
  num_episodes: 1
  num_substeps_per_step: 3  # Number of substeps in each simulation step
  device: "cpu"  # Specify the device: "cpu" or "cuda" for GPU
  visualize: False  # Optional: Include if the simulation has a visualization step

# Environment Configuration
environment:
  restock_threshold: 20  # Minimum stock before restocking
  restock_quantity: 100  # Units to restock
  products:
    - id: 1
      name: "Product A"
      price: 20
      stock: 100
    - id: 2
      name: "Product B"
      price: 15
      stock: 150
    - id: 3
      name: "Product C"
      price: 10
      stock: 200

# Promotions Configuration
promotions:
  - id: 1          # Product ID for the promotion
    discount: 0.2  # Discount rate (20%)
    duration: 7    # Duration of the promotion in steps
  - id: 2
    discount: 0.1  # Discount rate (10%)
    duration: 14

# Consumers Configuration
consumers:
  count: 50  # Number of consumers in the simulation
  budget_range:
    min: 50   # Minimum initial budget
    max: 200  # Maximum initial budget
  price_sensitivity_range:
    min: 0.5  # Minimum price sensitivity
    max: 1.5  # Maximum price sensitivity
  purchase_frequency_range:
    min: 2  # Minimum purchases per week
    max: 5  # Maximum purchases per week

# Substep Definitions
substeps:
  - type: observation
    name: restock
  - type: policy
    name: purchase
  - type: transition
    name: deliver


# State Configuration
state:
  agents:
    consumer: 50
  environment:
    products:
      - id: 1
        stock: 100
      - id: 2
        stock: 150
      - id: 3
        stock: 200
  time_step: 0
